### ISSUE TITLE
Unauthorized - check username/password

### ISSUE THREAD

**Issue by sebster6** [mwittig/pimatic-edimax#24]
I have an issue with a brand-new SP2101W. I can use the iOS app just fine, but I can't get the plug to work from Pimatic, always getting a "Unauthorized: check username/password" message. I tried changing passwords, plug name and everything else I can think of, to no avail.

Pimatic log output:
error [pimatic-edimax]: [EdimaxSmartPlug#GartenhausEdi-1] Unable to get model info of device: Error: Unauthorized: check username/password, Retrying ...
error [pimatic-edimax]: [EdimaxSmartPlug#GartenhausEdi-1] Unable to get schedule state of device: Error: Unauthorized: check username/password

And this is the debug output from pimatic-edimax:
`REQUEST OPTIONS: {"timeout":10000,"port":10000,"path":"smartplug.cgi","method":"POST","headers":{"Content-Type":"application/xml","Content-Length":187,"Authorization":"Basic YWRtaW46dGVzdHRlc3Q="},"username":"admin","password":"testtest","name":"GartenhausEdi","host":"192.168.178.77","agent":false}`
`REQUEST: <?xml version="1.0" encoding="UTF8"?><SMARTPLUG id="edimax"><CMD id="get"><SYSTEM_INFO><Run.Cus/><Run.Model/><Run.FW.Version/><Run.LAN.Client.MAC.Address/></SYSTEM_INFO></CMD></SMARTPLUG>`
`STATUS: 401`
`HEADERS: {"www-authenticate":"Digest realm=\"SP2101W\", nonce=\"7e245bb4859fdf91f6b47d500bc5f20d\", qop=\"auth\"","content-type":"text/html","content-length":"333","connection":"close","date":"Wed, 26 Apr 2017 22:13:43 GMT","server":"lighttpd/1.4.31-devel-325M"}`
`ERROR:Host 192.168.178.77 Error: Unauthorized: check username/password`

The name of the plug is "GartenhausEdi", password is "testtest" and it's running on 192.168.178.77.

By the way, when I enter http://192.168.178.77:10000/smartplug.cgi in my browser I get a login prompt and can successfully log in using "admin"/"testtest"... this is really weird.

The plug is running firmware 2.08. By the way, I have to use the "EdiLife" iOS app, because the EdiPlug tells me the plug isn't compatible with the firmware (don't know if this is related).
Running the plugin version 0.3.15 on a recent Pimatic installation.

Edit:
Found some info, it seems to be related to the most recent firmware version 2.04, which doesn't allow basic authentification anymore: https://knx-user-forum.de/forum/öffentlicher-bereich/knx-eib-forum/880356-wifi-wlan-steckdose-schalten-per-knx-hs-geschaltene-steckdosen-nachzurüsten

**Comment by mwittig** [comment]
Thank you very much for your report and your research on the matter! The knx-forum thread provides useful information. I have already implemented digest auth on another project, so this should not be a hurdle. The tricky bit may be to provde backwards compatibilty. Hopefully. it is possible to use a digest auth with fallbac basic auth which thn should server both new and old firmwares.

**Comment by sebster6** [comment]
No worries, in the meantime I'll try a downgrade to the previous version [[1]](https://www.loxforum.com/forum/faqs-tutorials-howto-s/14891-howto-wlan-steckdose-in-loxone-integrieren-f%C3%BCr-z-b-weihnachtsbeleuchtung?p=94077#post94077) to make it work in Pimatic.

**Comment by sebster6** [comment]
Works perfectly after downgrading to SP2101W_EDIMAX_2.03_20151012_upg.bin!

**Comment by mwittig** [comment]
Released  pimatic-edimax@0.3.16. The new version is expected to work seamlessly with older firmware versions demand basic authentication and the current firmware versions! tested with SP-2101W v2.03 and v2.08. 

Neverthess it'd be nice if you could send me the v2.03 image to WittigMarcus <at> gmail.com for future testing. Thanks

**Comment by camueller** [comment]
@sebster6 How did you manage to downgrade to 2.03? I downloaded http://www.edimax-de.eu/edimax/mw/cufiles/files/download/Driver_Utility/SP-2101W_Firmware_Upgrade_Tool_2.03.zip but the upgrade button remains disabled while the status says something like "Already up-to-date". The current version is displayed as 2.08.

**Comment by mwittig** [comment]
Actually, there is no need to downgrade as the current version of pimatic-edimax runs fine with fw version 2.08. If you still want to downgrade for whatever reason, a description on how to do it is provided in the aforementioned thread: <https://www.loxforum.com/forum/faqs-tutorials-howto-s/14891-howto-wlan-steckdose-in-loxone-integrieren-f%C3%BCr-z-b-weihnachtsbeleuchtung>.  **EDIT**: Btw, the 2.03 firmware had been provided by Edimax Support to some customers as they had problems with new version. Firmware downgrade does not seem to be officially supported by Edimax as far as I can tell.

**Comment by tutorialevideo** [comment]
Can we set up a static ip on edimax smart plug?
