### ISSUE TITLE
after updating pimatic & pimatic-edimax

### ISSUE THREAD

**Issue by buttonger** [mwittig/pimatic-edimax#3]
[EdimaxSmartPlug#sp1] Unable to get model info of device: Error: Request timeout occurred - request aborted, Retrying ...

Only updated the two packages. Nothing else. Should I provide some more information?

**Comment by mwittig** [comment]
Please try to ping the SmartPlug from the Pimatic host. If this doesn't work please unplug the SmartPlug, wait for 10 seconds, and plug it in again.

**Comment by mwittig** [comment]
No feedback from @buttonger - assuming this had been solved - re-open othwerwise
